debug-publish

diff --git a/.github/workflows/publish-images.yml b/.github/workflows/publish-images.yml
--- a/.github/workflows/publish-images.yml
+++ b/.github/workflows/publish-images.yml
@@ -37,6 +37,13 @@ jobs:
         uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
         with:
           cosign-release: 'v1.13.1'
+      
+      # Caches Docker images between builds
+      # https://github.com/marketplace/actions/docker-cache
+      - name: Cache Docker images.
+        uses: ScribeMD/docker-cache@0.3.3
+        with:
+          key: "docker-${{ runner.os }}"
 
       # Login against a Docker registry except on PR
       # https://github.com/docker/login-action
@@ -55,14 +62,11 @@ jobs:
         id: build-and-push
         uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
         with:
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
           script: |
             $InformationPreference = 'Continue'
             $imgs = images/build.ps1 -docker_registry_user '${{ vars.REGISTRY_USERNAME }}'
             Write-Host $imgs
-            Set-ActionVariable TAGS ($imgs.tag -join " ")
-            Set-ActionVariable DIGESTS ($imgs.digest -join " ")
+            Set-ActionVariable IMGS ($imgs | ConvertTo-Json)
 
       # Sign the resulting Docker image digest except on PRs.
       # This will only write to the public Rekor transparency log when the Docker
@@ -71,13 +75,21 @@ jobs:
       # https://github.com/sigstore/cosign
       - name: Sign the published Docker image
         if: ${{ github.event_name != 'pull_request' }}
+        uses: Amadevus/pwsh-script@97a8b211a5922816aa8a69ced41fa32f23477186
         env:
           COSIGN_EXPERIMENTAL: "true"
         # This step uses the identity token to provision an ephemeral certificate
         # against the sigstore community Fulcio instance.
-        run: |
-          IFS=' ' read -ra tags <<< "$TAGS"
-          IFS=' ' read -ra digests <<< "$DIGESTS"          
-          for i in "${!tags[@]}"; do
-              cosign sign "${tags[$i]}@${digests[$i]}"
-          done
+        with:
+          script: |
+            $imgs = $env:IMGS | ConvertFrom-Json
+            $imgs | ForEach-Object {
+              $ret = docker buildx imagetools inspect $_.tag |`
+                ConvertFrom-Csv -Delimiter ":" -Header @('k', 'v', 'd')
+              $digest = $ret | Where-Object k -EQ 'Digest' | Select-Object -ExpandProperty d
+              cosign sign "$($_.tag)@$($digest)"
+            }
+
+      # - name: Setup tmate session
+      #   if: success() || failure()
+      #   uses: mxschmitt/action-tmate@v3
